author: "Dein Honour Davies"

profession:
  - Geoscientist
  - Data Scientist
  - Physics Educator

email: ""

github: "https://github.com/dhdaviescode-star"

linkedin: "https://www.linkedin.com/in/dein-davies-522490412"

youtube: ""