title: Dein Honour Davies

tagline: >
  Geoscientist • Data Scientist • Physics Educator

description: >
  Official website of Dein Honour Davies featuring research,
  AI, geoscience, physics education, machine learning,
  software development and scientific computing.

email: dhdavies.code@gmail.com

website: https://dhdaviescode-star.github.io/dein-davies-website

github: https://github.com/dhdaviescode-star

linkedin: https://www.linkedin.com/in/dein-davies-522490412/

facebook: https://www.facebook.com/dhdavies.code

youtube:

researchgate:

newsletter:

copyright: 2026

author: Dein Honour Davies